### ISSUE TITLE
Unable to install theme

### ISSUE THREAD

**Issue by skalyan91** [dylanaraps/Flatabulous-wal#1]
I'm on Ubuntu 16.04. I've downloaded the zip file, and extracted the folder `Flatabulous-wal` under `~/.themes/`. However, if I go to unity-tweak-tool (or gnome-tweak-tool, for that matter), I am unable to see any theme named "Flatabulous-wal". What could I be doing wrong? I've also tried putting the theme folder under `~/.local/share/themes/` and other such possibilities, but with no luck.

**Comment by dylanaraps** [comment]
The correct directory is `~/.themes/` (not `~/.local/share/themes`), can you send me a screenshot of what's inside your `~/.themes/` directory?

**Comment by skalyan91** [comment]
Just 1 folder: Flatabulous-wal (renamed from Flatabulous-wal-master).

**Comment by dylanaraps** [comment]
Try using `lxappearance` to set the theme and let me know if that works.

**Comment by skalyan91** [comment]
OK, I am able to see Flatabulous-wal using lxappearance, but I'm not able
to apply the theme. Maybe it just doesn't work under Unity.

**Comment by dylanaraps** [comment]
The theme only works with GTK2 for now. (*It won't theme anything Unity specific which is probably why it isn't showing up in the Unity theme switcher.*)

**Comment by skalyan91** [comment]
I suspected as much. Thanks for looking into this.
