### ISSUE TITLE
Can't find theme in gnome-tweak-tool.

### ISSUE THREAD

**Issue by MasterTextman** [dylanaraps/Flatabulous-wal#2]
I put the folder in ~/.themes, and I even tried putting it in /usr/share/themes, but I cannot find it in gnome-tweak-tool. I also tried installing gtk-2.0, but even then it didn't work.

**Comment by dylanaraps** [comment]
There's only a GTK2 theme so it won't appear in the GNOME theme switcher. I haven't had time to create a GNOME theme etc.
